### ISSUE TITLE
Improve the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m1-evaluacion-intermedia-younglust#1]
Super @younglust !!!

Here you have some tips to improve the exercise:

- [x] Fix the language of the page
- [x] You have an extra `div` inside `header` that can be removed ;) Add the classes to the header.
- [x] Only use tag selectors to reset styles.
- [x] `title` attribute on `a` tags is not meant to duplicate the content of the links, maybe this post will clarify it a little https://www.searchenginejournal.com/how-to-use-link-title-attribute-correctly/#close
- [x] Do not use flex attributes when the item is not flex or a flex child.
- [x] Avoid capital on HTML texts, we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text

Let me know if you have any doubts ;)

Go for it!!

**Comment by younglust** [comment]
Hello @nasivuela I tried to fix all the requirements, but I'm not sure what means this:
- Only use tag selectors to reset styles
- Improve hierarchy adding more common styles... (I think this's done)

Thanks a lot! :)

**Comment by nasivuela** [comment]
Ey @younglust, you are right, those two points were already done. Maybe I was looking to an older version?

Anyway, it looks like a well-done job to me!

![](https://media.giphy.com/media/NEvPzZ8bd1V4Y/giphy.gif)
